version: '3.9'

services:

  mongo_db:
    image: mongo:latest
    restart: always
    command: mongod --logpath /dev/null
    logging:
        driver: "none"
    volumes:
      - mongo_db:/data/mongo_db
  
  legbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
    - mongo_db

volumes:
  mongo_db: {}
