name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to <your domain>
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.remote_user }}
        host: ${{ secrets.remote_host }}
        key: ${{ secrets.remote_key }}
        script: 'cd ~/LegBot && ./rebuild.sh'