name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to ubuntu
      uses: shimataro/ssh-key-action@v2
      with:
        username: ${{ secrets.REMOTE_USER }}
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.REMOTE_KEY }}
        script: 'cd ~/LegBot && ./rebuild.sh'